flowchart LR
    A(A node with round edges)
    B([A stadium-shaped node])
    C[[A node in a subroutine shape]]
    D[(Database)]
    E((A node in the form of a circle))
    F>A node in an asymmetric shape]
    G{A node in a rhombus}
    H{{A hexagon node}}
    I[/Parallelogram/]
    J[\Parallelogram alt\]
    K[/Trapezoid\]
    L(((Double circle)))
    A[Start] --> B{Is it?}
    B -->|Yes| C[OK]
    C --> D[Rethink]
    D --> B
    B ---->|No| E[End]